### ISSUE TITLE
Can you give write rights?

### ISSUE THREAD

**Issue by etpinard** [a-vis/gl-text#1]
cc @dy !

**Comment by etpinard** [comment]
Commit https://github.com/a-vis/gl-text/commit/bf7e32af62398998f3ae033b16b025f71d58a89b breaks plotly.js in Electron (`document.body === null`) for some reason when the `<script>` is evaluated.

**Comment by etpinard** [comment]
![image](https://user-images.githubusercontent.com/6675409/42332457-015e4b5e-8046-11e8-960b-d4dacdb849d0.png)

appears to fix things.

**Comment by dy** [comment]
Whoops!
Sorry, added!
